version: "3.5"

services:
  web:
    image: nm0829/lohub-api
    ports:
      - "${PORT}:3000"
    env_file:
      - .env
    networks:
      - lohub
    restart: always
    depends_on:
      - "postgres"
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      lohub:
        aliases:
          - postgres.db
    volumes:
      - postgres:/var/lib/postgresql/lohub-data
volumes:
  postgres:
    driver: local
networks:
  lohub:
